### ISSUE TITLE
Bump version and release?

### ISSUE THREAD

**Issue by rivy** [uutils/uucore#5]
I'm getting build failures on coreutils from the `0.0.1` version.

When building with the patched update, everything looks good. I'd like to bump the version on coreutils to `uucore 0.0.2` (or `uucore 0.1.0`?) to remove the pin on that specific patched commit.

Thanks.

**Comment by rivy** [comment]
Version is now bumped to v0.0.2 (with some fixes in branch `t`).

@Arcterus , I'm planning to push this to `master` in the next couple of days if that's alright.

And, can you `cargo publish` this please (after it's pushed to `master`)?

I don't believe anyone else has permissions to push it to crates.io (you're the sole owner per the [uucore crates.io web page](https://crates.io/crates/uucore)).

**Comment by rivy** [comment]
Pushed to `master`.
@Arcterus , this still needs a `cargo publish`.
A co-owner or two would be also helpful to push to crates.io in the future.

**Comment by sylvestre** [comment]
@Arcterus ping? thanks

**Comment by sylvestre** [comment]
@Arcterus could you please give us permissions? 
user on crates.io => https://crates.io/users/sylvestre
many thanks

**Comment by sylvestre** [comment]
Many thanks. I sent an invite to @rivy and uploaded 0.0.2
